[workspace]
resolver = "2"
members = [ "experiments/boids", "experiments/game_of_life", "experiments/moving", "experiments/rays", "monarchs"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
