[package]
name = "monarchs"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15", features = ["wayland", "dynamic_linking"] }
bevy_framepace = "0.18"
bevy_egui = { version = "0.33" }
bevy_obj = "0.15"

egui_extras = "0.31"
